/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Test_ReedSolomonC */

#ifndef _Included_Test_ReedSolomonC
#define _Included_Test_ReedSolomonC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test_ReedSolomonC
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Test_ReedSolomonC_init
  (JNIEnv *, jclass);

/*
 * Class:     Test_ReedSolomonC
 * Method:    rsNew
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_Test_ReedSolomonC_rsNew
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Test_ReedSolomonC
 * Method:    rsRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Test_ReedSolomonC_rsRelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Test_ReedSolomonC
 * Method:    rsEncode
 * Signature: (J[JI)V
 */
JNIEXPORT void JNICALL Java_Test_ReedSolomonC_rsEncode
  (JNIEnv *, jobject, jlong, jlongArray, jint);

/*
 * Class:     Test_ReedSolomonC
 * Method:    rsReconstruct
 * Signature: (J[J[ZI)V
 */
JNIEXPORT void JNICALL Java_Test_ReedSolomonC_rsReconstruct
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jint);

#ifdef __cplusplus
}
#endif
#endif
